extends:
  - eslint:recommended
  - plugin:unicorn/all
  - plugin:@typescript-eslint/recommended
  - plugin:solid/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  # - solid
  - '@typescript-eslint'
rules:
  # 0 = off
  # 1 = warn
  # 2 = error

  #region eslint
  indent: [2, 2, { SwitchCase: 1 }]
  #endregion

  #region eslint-plugin-unicorn
  unicorn/filename-case: 0
  unicorn/no-keyword-prefix: 0
  unicorn/prevent-abbreviations: 0
  # TODO resolve
  unicorn/no-null: 0
  unicorn/numeric-separators-style: 0
  #endregion